{
  "@context": "https://openvex.dev/ns/v0.2.0",
  "@id": "semaphoreui--semaphore-1684bc9dfb4b8bf3ae235b15737ce02cfd2668349c9ed49491a531686828fabb",
  "author": "Nicholas Ward (CACI-Senior Cyber Engineer)",
  "role": "Document Creator",
  "timestamp": "2025-10-17T20:47:19.248217Z",
  "verions": 1,
  "statements": [
    {
      "vulnerability": {
        "name": "CVE-2025-8869",
        "description": "When extracting a tar archive pip may not check symbolic links point into the extraction directory if the tarfile module doesn't implement PEP 706.\nNote that upgrading pip to a \"fixed\" version for this vulnerability doesn't fix all known vulnerabilities that are remediated by using a Python version that implements PEP 706.\n\nNote that this is a vulnerability in pip's fallback implementation of tar extraction for Python versions that don't implement PEP 706\nand therefore are not secure to all vulnerabilities in the Python 'tarfile' module. If you're using a Python version that implements PEP 706\nthen pip doesn't use the \"vulnerable\" fallback code.\n\nMitigations include upgrading to a version of pip that includes the fix, upgrading to a Python version that implements PEP 706 (Python >=3.9.17, >=3.10.12, >=3.11.4, or >=3.12),\napplying the linked patch, or inspecting source distributions (sdists) before installation as is already a best-practice."
      },
      "products": [
        {
          "@id": "pkg:oci/semaphore?repository_url=index.docker.io%2Fsemaphoreui%2Fsemaphore",
          "subcomponents": [
            {
              "@id": "pkg:pypi/pip@25.2"
            }
          ]
        }
      ],
      "status": "not_affected",
      "status_notes": "this is a METADATA/NOTE CVE not an actual vulnerable",
      "justification": "component_not_present",
      "impact_statement": "This is a METADATA remanance of pip known to be used during the build process but is no longer present in final build",
      "timestamp": "2025-10-17T20:47:19Z"
    },
    {
      "vulnerability": {
        "name": "CVE-2025-47907",
        "description": "Cancelling a query (e.g. by cancelling the context passed to one of the query methods) during a call to the Scan method of the returned Rows can result in unexpected results if other queries are being made in parallel. This can result in a race condition that may overwrite the expected results with those of another query, causing the call to Scan to return either unexpected results from the other query or an error."
      },
      "products": [
        {
          "@id": "pkg:oci/semaphore?repository_url=index.docker.io%2Fsemaphoreui%2Fsemaphore",
          "identifiers": {
            "purl": "pkg:golang/github.com/hashicorp/terraform"
          },
          "subcomponents": [
            {
              "@id": "pkg:golang/stdlib@v1.23.3"
            }
          ]
        },
        {
          "@id": "pkg:oci/semaphore?repository_url=index.docker.io%2Fsemaphoreui%2Fsemaphore",
          "identifiers": {
            "purl": "pkg:golang/github.com/gruntwork-io/terragrunt@v0.78.0"
          },
          "subcomponents": [
            {
              "@id": "pkg:golang/stdlib@v1.23.5"
            }
          ]
        }
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_in_execute_path",
      "impact_statement": "the products listed as being affected by this CVE do not contain the vulnerable module of the listed subcomponent library.",
      "timestamp": "2025-10-17T20:47:19Z"
    }
  ]
}